import { useQuery } from 'react-query';
import { ICommon } from '../../interfaces/common/common.interface';

const QUERY_KEY = 'bankList';

const useBankList = () => {
  const valueItems: ICommon.ValueItem[] = [
    { text: '우리은행', value: '우리은행' },
    { text: '국민은행', value: '국민은행' },
    { text: '기업은행', value: '기업은행' },
    { text: '농협은행', value: '농협은행' },
    { text: '신한은행', value: '신한은행' },
    { text: '하나은행', value: '하나은행' },
    { text: '한국씨티은행', value: '한국씨티은행' },
    { text: 'SC제일은행', value: 'SC제일은행' },
    { text: '경남은행', value: '경남은행' },
    { text: '광주은행', value: '광주은행' },
    { text: '대구은행', value: '대구은행' },
    { text: '도이치은행', value: '도이치은행' },
    { text: '부산은행', value: '부산은행' },
    { text: '비엔피파리바은행', value: '비엔피파리바은행' },
    { text: '산림조합', value: '산림조합' },
    { text: '산업은행', value: '산업은행' },
    { text: '새마을금고', value: '새마을금고' },
    { text: '수출입은행', value: '수출입은행' },
    { text: '수협은행', value: '수협은행' },
    { text: '신협', value: '신협' },
    { text: '우체국', value: '우체국' },
    { text: '저축은행', value: '저축은행' },
    { text: '전북은행', value: '전북은행' },
    { text: '제주은행', value: '제주은행' },
    { text: '중국건설은행', value: '중국건설은행' },
    { text: '중국공상은행', value: '중국공상은행' },
    { text: '중국은행', value: '중국은행' },
    { text: '지역농축협', value: '지역농축협' },
    { text: '카카오뱅크', value: '카카오뱅크' },
    { text: '케이뱅크', value: '케이뱅크' },
    { text: '토스뱅크', value: '토스뱅크' },
    { text: 'BOA', value: 'BOA' },
    { text: 'HSBC은행', value: 'HSBC은행' },
    { text: 'JP모간체이스은행', value: 'JP모간체이스은행' },
    { text: '지방세입', value: '지방세입' },
    { text: '국고금납부', value: '국고금납부' },
    { text: 'NH투자증권', value: 'NH투자증권' },
    { text: '교보증권', value: '교보증권' },
    { text: '다올투자증권', value: '다올투자증권' },
    { text: '대신증권', value: '대신증권' },
    { text: '메리츠증권', value: '메리츠증권' },
    { text: '미래에셋증권', value: '미래에셋증권' },
    { text: '부국증권', value: '부국증권' },
    { text: '삼성증권', value: '삼성증권' },
    { text: '신영증권', value: '신영증권' },
    { text: '신한투자증권', value: '신한투자증권' },
    { text: '아이엠투자증권', value: '아이엠투자증권' },
    { text: '유안타증권', value: '유안타증권' },
    { text: '유진투자증권', value: '유진투자증권' },
    { text: '이베스트투자증권', value: '이베스트투자증권' },
    { text: '카카오페이증권', value: '카카오페이증권' },
    { text: '케이프투자증권', value: '케이프투자증권' },
    { text: '키움증권', value: '키움증권' },
    { text: '토스중권', value: '토스중권' },
    { text: '하나증권', value: '하나증권' },
    { text: '하이투자증권', value: '하이투자증권' },
    { text: '한국투자증권', value: '한국투자증권' },
    { text: '한국포스증권', value: '한국포스증권' },
    { text: '한화투자증권', value: '한화투자증권' },
    { text: '현대차증권', value: '현대차증권' },
    { text: 'BNK증권', value: 'BNK증권' },
    { text: 'DB금융투자', value: 'DB금융투자' },
    { text: 'IBK투자증권', value: 'IBK투자증권' },
    { text: 'KB증권', value: 'KB증권' },
    { text: 'SK증권', value: 'SK증권' },
  ];
  
  return useQuery(QUERY_KEY, () => Promise.resolve(valueItems), {
    staleTime: 100000,
  });
};

export default useBankList;