name: Next.js Build And Deploy Production

on:
  push:
    tags:
      - production-*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@main

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate Config Files
        run: |
          echo "$ENV_LOCALHOST" >> .env.localhost
          echo "$ENV_DEVELOPMENT" >> .env.development
          echo "$ENV_PRODUCTION" >> .env.production

      - name: npm i
        run: npm i

      - name: npm run build
        run: npm run build

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: aws lightsail ip, port open
        run: |
          aws lightsail open-instance-public-ports \ 
            --instance-name "${{ INSTANCE_NAME }}" \ 
            --port-info fromPort=${{ secrets.REMOTE_SSH_PORT }},protocol=TCP,toPort=${{ secrets.REMOTE_SSH_PORT }},cidrs="${{ steps.ip.outputs.ipv4 }}"

      - name: (scp) .next folder to ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          source: ".next"
          target: "/home/projects/gofield-frontend/.next.new"

      - name: .next.new/.next folder move and ec2 server folder name change
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            sh /home/projects/gofield-frontend/sh/deploy.sh